import { withBasePath } from "../../../site-path";

export default function ProstheticDesign(){return <main className="case-page">
  <nav className="case-nav"><a href={withBasePath("/")}>← Portfolio</a><a href={withBasePath("/projects/prosthetic-foot/validation/")}>Prototype & validation →</a></nav>
  <header className="case-hero prosthetic-hero"><p className="kicker">Page 1 of 2 · Design & simulation</p><h1>Designing a paediatric prosthetic foot</h1><p>A four-person engineering project to create a passive foot for a three-year-old child weighing 16 kg and wearing size 27 shoes.</p></header>
  <section className="case-metrics"><div><strong>3 years</strong><span>target user age</span></div><div><strong>16 kg</strong><span>reference mass</span></div><div><strong>Size 27</strong><span>shoe constraint</span></div><div><strong>800 N</strong><span>validation load</span></div></section>
  <section className="case-section two-column"><div><p className="kicker">The engineering problem</p><h2>Flexible enough to walk. Strong enough to remain safe.</h2></div><div><p>The foot had to fit inside a child&apos;s shoe, connect to a Proteor 1K206 four-hole adapter and deform like an ankle during walking. The safety load was set to 800 N—four times the representative 200 N walking load.</p><p>Within a four-person team, we translated these needs into measurable requirements, analytical calculations, CAD geometry and finite-element simulations.</p></div></section>
  <section className="visual-pair"><figure><img className="design-image" src={withBasePath("/projects/prosthetic/final-cad.png")} alt="Final prosthetic foot CAD model"/><figcaption>Final CAD geometry with the flexible internal structure.</figcaption></figure><figure><img className="design-image" src={withBasePath("/projects/prosthetic/fea-final.png")} alt="Finite element simulation of the foot"/><figcaption>Finite-element analysis under the validation loading configuration.</figcaption></figure></section>
  <section className="case-section two-column"><div><p className="kicker">Design choices</p><h2>One printable part, built around real interfaces.</h2></div><div><ul className="case-list"><li>Passive foot-and-ankle replacement for a transtibial prosthesis.</li><li>PLA part manufactured by FDM on a Raise3D E2 printer.</li><li>Geometry sized for a maximum envelope of 17.5 × 6 cm.</li><li>Mechanical interface designed around the Proteor adapter.</li><li>Simulation refined before producing the final prototype.</li></ul></div></section>
  <section className="next-page"><p>Continue with the physical prototype and the client validation tests.</p><a className="pink-button" href={withBasePath("/projects/prosthetic-foot/validation/")}>Open page 2 →</a></section>
</main>}
