import { withBasePath } from "../../../site-path";

export default function ProstheticValidation(){return <main className="case-page">
  <nav className="case-nav"><a href={withBasePath("/projects/prosthetic-foot/design/")}>← Design & simulation</a><a href={withBasePath("/")}>Portfolio</a></nav>
  <header className="case-hero prosthetic-hero"><p className="kicker">Page 2 of 2 · Prototype & validation</p><h1>From the digital model to a tested prototype</h1><p>The final PLA demonstrator was printed, assembled with its adapter and tested under the client&apos;s acceptance protocol.</p></header>
  <section className="case-metrics"><div><strong>5 / 5</strong><span>requirements validated</span></div><div><strong>800 N</strong><span>without failure</span></div><div><strong>17.6 mm</strong><span>deflection at 200 N</span></div><div><strong>&lt; 8%</strong><span>stiffness variation limit</span></div></section>
  <section className="visual-pair"><figure><img src={withBasePath("/projects/prosthetic/prototype-validation.png")} alt="Finished 3D-printed paediatric prosthetic foot with its metal adapter"/><figcaption>The finished PLA prototype.</figcaption></figure><figure><img src={withBasePath("/projects/prosthetic/load-test.png")} alt="Prosthetic foot on mechanical test machine"/><figcaption>Mechanical loading test at the specified 20° configuration.</figcaption></figure></section>
  <section className="case-section two-column"><div><p className="kicker">Concrete result</p><h2>The prototype passed every acceptance criterion.</h2></div><div><ul className="case-list"><li>No crack or break during three loading cycles up to 800 N.</li><li>Stiffness stayed within the required 8% variation limit.</li><li>Measured deflection at 200 N: 17.6 mm, close to the 16.9 mm target.</li><li>The prototype fitted inside a size 27 shoe.</li><li>The four-hole adapter interface was physically validated.</li></ul></div></section>
  <section className="visual-pair compact"><figure><img src={withBasePath("/projects/prosthetic/shoe-fit-test.png")} alt="Prototype fitted inside a child size shoe"/><figcaption>Size 27 shoe fit check.</figcaption></figure><figure><img className="adapter-interface-image" src={withBasePath("/projects/prosthetic/adapter-interface.png")} alt="Four-hole prosthetic adapter fitted to prototype"/><figcaption>Proteor-compatible adapter interface.</figcaption></figure></section>
  <section className="case-callout"><span>What this proves</span><p>The project connected requirements, modelling, manufacturing and experimental validation—not just a CAD rendering.</p></section>
  <footer className="case-footer"><a href={withBasePath("/projects/prosthetic-foot/design/")}>← Review the design</a><a href={withBasePath("/")}>All projects →</a></footer>
</main>}
